;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #171a1f
foreground = #f2f2f2
sep = #5B6579

white = #FFFFFF
black = #000000
red = #80ABD6
pink = #9BBDDC
purple = #436EAB
blue = #42A5F5
cyan = #4DD0E1
teal = #00B19F
green = #9BBDDC
lime = #6592C6
yellow = #FDD835
amber = #FBC02D
orange = #a2bed7
brown = #AC8476
indigo = #6C77BB
gray = #9E9E9E
blue-gray = #6D8895

charcoal = #323b3f
light-blue = #9bbfbf
light = #171a1f
gray2 = #444444
bruh-pink = #de7cde

dark1 = #11999E
normal1 = #30E3CA
light1 = #71C9CE
light2 = #A6E3E9
light3 = #E3FDFD



;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
