# Shell variables
# Generated by 'wal'
wallpaper='/home/lucid/.wall/ev1.jpg'

# Special
background='#04060A'
foreground='#b0a4be'
cursor='#b0a4be'

# Colors
color0='#04060A'
color1='#4D4458'
color2='#644F5C'
color3='#524E6A'
color4='#6E596B'
color5='#726877'
color6='#7E8B6E'
color7='#b0a4be'
color8='#7b7285'
color9='#4D4458'
color10='#644F5C'
color11='#524E6A'
color12='#6E596B'
color13='#726877'
color14='#7E8B6E'
color15='#b0a4be'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
