--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lucid/.wall/ev1.jpg"

-- Special
background="#04060A"
foreground="#b0a4be"
cursor="#b0a4be"

-- Colors
color0="#04060A"
color1="#4D4458"
color2="#644F5C"
color3="#524E6A"
color4="#6E596B"
color5="#726877"
color6="#7E8B6E"
color7="#b0a4be"
color8="#7b7285"
color9="#4D4458"
color10="#644F5C"
color11="#524E6A"
color12="#6E596B"
color13="#726877"
color14="#7E8B6E"
color15="#b0a4be"
